config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from main import views

app_name = "api"

urlpatterns = [
    path("", views.companies_view, name="companies"),
    path("add_employee/<int:company_id>", views.add_employee, name="add_employee"),
]

main/models.py
from django.db import models


class Company(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100)


class Employee(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    comment = models.TextField()
    company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

main/forms.py
from django import forms
from main import models


class AddEmployee(forms.Form):
    all_employees = models.Employee.objects.all()
    show_employees = []

    for employee in all_employees:
        if not employee.company:
            show_employees.append(
                [employee.id, employee.first_name + " " + employee.last_name]
            )
    employees = forms.ChoiceField(required=True, choices=show_employees)
    employees.widget.attrs.update({"class": "form-select"})

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from main import models
from . import forms

# Create your views here.


def companies_view(request):
    companies = models.Company.objects.all()
    employees = models.Employee.objects.all()
    return render(request, "companies.html", {"companies": companies, "employees":employees})


def add_employee(request, company_id):
    company = models.Company.objects.get(id=company_id)
    if request.method == "POST":
        form = forms.AddEmployee(request.POST)
        if form.is_valid():
            employee = models.Employee.objects.get(id = form.cleaned_data["employees"])
            employee.company = company
            employee.save()
            return HttpResponseRedirect("/")
    else:
        form = forms.AddEmployee()
    return render(request, "add_employee.html", {"form": form, "company":company})

templates/add_employee.html
{% extends 'layout.html' %}

{% block body %}
<h3>Add to {{ company.name }}</h3>
<div style="width: 60%;">
    <form action="{% url 'api:add_employee' company.id %}" class="form-control" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input name="submit_bid" type="submit" class="btn btn-primary">
    </form>

</div>
{% endblock body %}

templates/companies.html
{% extends 'layout.html' %}
{% block body %}

<!-- <div class="container justify-content-center mt-4"> -->

<table>
    <tr>
        <th style="width: 20%;">Company</th>
        <th>Employees</th>
    </tr>
    {% for company in companies %}
    <tr>
        <td>{{ company.name }} <a href="{% url 'api:add_employee' company.id %}">(Add Employee)</a></td>
        <td>{% for employee in employees %}
            {% if employee.company.name == company.name %}
            {{ employee.first_name }} {{ employee.last_name}},
            {% endif %}
            {% endfor %}
        </td>
    </tr>
    {% endfor %}
</table>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <title>Companies List</title>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 70%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }
    </style>
</head>

<body>
    <ul class="nav nav-underline justify-content-center">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Companies</a>
        </li>
    </ul>
    <center class="mt-5">

        {% block body %}
        {% endblock body %}

    </center>
</body>

</html>